### ISSUE TITLE
Pod not supported on Fargate: fields not supported: HostNetwork, port contains HostIP or HostPort

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws-samples/eks-efs-share-within-fargate#5]
Our EKS cluster runs only on Fargate and when I add these lines:
```
  enable_aws_efs_csi_driver = true
  aws_efs_csi_driver = {
     regionalStsEndpoints = true
  }
```

I got the following error:
`Pod not supported on Fargate: fields not supported: HostNetwork, port contains HostIP or HostPort`

I [read](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/589#issuecomment-1018617824) that if you are using Fargate you do not need the controller. But if I do not deploy the controller, then on creating PVC, I get the following error:
```
0s          Warning   FailedAttachVolume   Pod/apigw-control-plane-5fd6c94569-wt2w6    AttachVolume.Attach failed for volume "apigw-cnt-pv" : timed out waiting for external-attacher of efs.csi.aws.com CSI driver to attach volume fs-04261bafa10da96c8
0s          Warning   FailedMount          Pod/apigw-control-plane-5fd6c94569-wt2w6    Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage], failed to process volumes=[]: timed out waiting for the condition

```

**Environment**
- Kubernetes version (use `kubectl version`):
- Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6-eks-f8587cb
- Driver version:
helm-chart-aws-efs-csi-driver-2.4.8

**Comment by rodrigobersa** [comment]
Hi @mostafafarzaneh!

Thanks for raising this issue!

We have 2 different errors, showing that the parameters not supported are related to the Pod network configuration `HostNetwork`, port contains `HostIP` or `HostPort`.

I believe that the Pod not being able to mount the volume is a consequence of that, and not the cause. Can you try to validate and spin up the Pod again without those?

Best,

**Comment by coolguy** [comment]
This exact same issue also happens to me.
EKS Fargate with 
enable_aws_efs_csi_driver = true

Controller shown as pending:
```
kube-system                  efs-csi-controller-54b8d456b8-h5j8f             0/3     Pending   0          85d
kube-system                  efs-csi-controller-54b8d456b8-qq4bb             0/3     Pending   0          85d
```

With those errors:
```
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  19m    fargate-scheduler  Pod not supported on Fargate: fields not supported: HostNetwork, port contains HostIP or HostPort
  Warning  FailedScheduling  5m35s  fargate-scheduler  Pod not supported on Fargate: fields not supported: HostNetwork, port contains HostIP or HostPort
```


Although EFS volume is abled to be attached to a pod successfully.
